# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool: default

resources:
  pipelines:
    - pipeline: benchmarks
      source: mainrepo
      project: Benchmarks
      trigger:
        branches:
          - main

steps:
- checkout: self
  persistCredentials: true
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
- script: pip install -r requirements.txt
- script: asv continuous --interleave-processes -a processes=2 --split --show-stderr 'HEAD^' 'HEAD'
- script: |
    git config user.name "Github Bot"
    git config user.email "results_bot@github.com"
    git add -f results/*
    git commit -m "Results for ubuntu-22.04 added [skip ci]"
    git push origin
