name: Benchmark

on:
  pull_request:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 0 * * *'

jobs:
  run_benchmarks:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: cache Django
        uses: actions/cache@v3
        with:
          path: Django/*
          key: Django
      - name: Run Benchmarks
        run: |-
          asv machine --machine ubuntu-22.04 --yes
          asv run --skip-existing
      - name: Commit results
        if: github.event.pull_request != 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Github actions bot
          message: 'results for ubuntu-22.04 added  [skip ci]'
          pull: '--rebase --autostash'
          add: '-f results/*'

  call_publish_results_workflow:
      needs: run_benchmarks
      if: github.event.pull_request != 'true'
      uses: deepakdinesh1123/benchmarks/.github/workflows/publish-results.yml@main
