name: set status

on:
  pull_request:

jobs:
  Set_Status:
    runs-on: ubuntu-22.04
    steps:
      - name: Set status
        uses: "teamniteo/pull_request_status_action@v1.0.0"
        with:
          pr_number: ${{ github.event.number }}
          state: success
          repository: deepakdinesh1123/benchmarks
          description: 'BENCHMARKS NOT CHANGED SIGNIFICANTLY'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
