name: set status

on:
  push:

env:
  BENCHMARK-RESULT: 'BENCHMARKS NOT CHANGED SIGNIFICANTLY'

jobs:
  Set_Status:
    runs-on: ubuntu-22.04
    steps:
      - name: Set status
        uses: "teamniteo/pull_request_status_action@v1.0.0"
        with:
          pr_number: ${{ github.event.number }}
          state: success
          context: 'Benchmarks'
          repository: deepakdinesh1123/benchmarks
          description: $BENCHMARK-RESULT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
