name: set status

on:
  push:

jobs:
  Set_Status:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set result
        shell: bash -l {0}
        id: set_result
        run: cat out.txt >> $GITHUB_STEP_SUMMARY
