name: set status

on:
  push:

jobs:
  Set_Status:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Copy
        run: cat out.txt >> $GITHUB_ENV
      - name: Set result
        id: set_result
        run: |-
          if grep "PERFORMANCE DECREASED" $GITHUB_STEP_SUMMARY
          then
            echo "BENCHMARKS HAVE CHANGED SIGNIFICANTLY" >> $GITHUB_STEP_SUMMARY
          else
            echo "BENCHMARKS NOT CHANGED SIGNIFICANTLY" >> $GITHUB_STEP_SUMMARY
