name: set status

on:
  pull_request:

jobs:
  Set_Status:
    runs-on: ubuntu-22.04
    steps:
      - name: Set result
        id: set_result
        run: echo "::set-output name=result::BENCHMARKS NOT CHANGED SIGNIFICANTLY"
      - name: Set status
        id: set_status
        uses: "teamniteo/pull_request_status_action@v1.0.0"
        with:
          pr_number: ${{ github.event.number }}
          state: success
          context: 'Benchmarks'
          repository: deepakdinesh1123/benchmarks
          description: ${{ steps.set_result.outputs.result }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
