name: set status

on:
  push:

jobs:
  Set_Status:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set result
        shell: bash -l {0}
        id: set_result
        run: |-
          if grep -q "PERFORMANCE DECREASED" out.txt;
          then
            echo "BENCHMARKS HAVE CHANGED SIGNIFICANTLY"
          else
            echo "BENCHMARKS NOT CHANGED SIGNIFICANTLY"
          fi
