name: set status

on:
  pull_request:
    types: [reopened]



jobs:
  Set_Status:
    runs-on: ubuntu-22.04
    steps:
      - name: Intsall Requirements
        run: pip install requests
      - name: Set Status
        env:
          PR_NUM: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BENCHMARK-RESULT: "BENCHMARKS NOT CHANGED SIGNIFICANTLY"
        run: |
          python -c '
          import requests, os, json
          headers = {
            "Accept": "application/vnd.github.v3+json",
            "Authorization": f"token {os.environ['GITHUB_TOKEN']}",
          }
          payload = {
            "state": "success",
            "context": "Benchmarks",
            "description": f"{os.environ['BENCHMARK-RESULT']}",
          }
          url = f"https://api.github.com/repos/benchmarks/pulls/{os.environ.get('PR_NUM')}"
          response = requests.get(url, headers)
          status_url = response.json()["statuses_url"]
          response = requests.post(status_url, headers, data=json.dumps(payload))
          response.raise_for_status()
          '
